### ISSUE TITLE
ModuleNotFoundError: No module named 'resource'

### ISSUE THREAD

**Issue by ghost** [VinAIResearch/single_image_hdr#1]
File "C:\Users\MyPC\Downloads\single_image_hdr-main\single_image_hdr-main\infer_bracketed.py", line 12, in <module>
    from src.models.ednet import EDNet
  File "C:\Users\MyPC\Downloads\single_image_hdr-main\single_image_hdr-main\src\models\ednet.py", line 3, in <module>
    from resource import RUSAGE_CHILDREN, RUSAGE_SELF, getrusage
ModuleNotFoundError: No module named 'resource'

**Comment by hieultp** [comment]
Hi @avidews, [resource](https://docs.python.org/3.8/library/resource.html) is the built-in library in Python. I'm not sure what's causing the error as I have tested it on Ubuntu 22.04 only.

**Comment by ghost** [comment]
Will it work on Windows?

**Comment by hieultp** [comment]
I haven't tested the code on Windows yet. Though I think it should work fine if you run it on Windows Linux Subsystem.

**Comment by ghost** [comment]
I have a requirement to convert my 360 LDR 8bit images to 32bit HDR images for using them as an HDRI in 3D modelling software for lighting 3D models. Is this code doing something like this? Can you please share any sample output? If it covers my requirement, I would set up a Linux environment to get it working.

Any help is appreciated...

**Comment by hieultp** [comment]
While our code focuses on single-image HDR reconstruction, it may not directly handle 360 LDR to 32-bit HDR conversion and might not work well in 360 scenarios. I recommend exploring alternative tools or methods better suited for your specific task. Feel free to reach out if you have any further questions.

**Comment by ghost** [comment]
I believe that should work for me. 360 LDR is just like a normal LDR image bit with a higher resolution. I have read the paper and I feel it can work. I would love to give it a try, and I will let you know if I need anything.
