### ISSUE TITLE
ImportError: cannot import name 'get_num_classes' 

### ISSUE THREAD

**Issue by Dokhyam** [VinAIResearch/single_image_hdr#2]
Hi,

I'm using the conda env you supplied to run the inference code but it gives me this Import Error:
ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data'
Do you know what could be causing this and how I can fix it?

Thanks!

**Comment by hieultp** [comment]
Hi, this might be a problem related to the pytorch-lighting version. I think the similar issue below could solve your problem.
https://github.com/astra-vision/MonoScene/issues/18#issuecomment-1105392836

**Comment by Dokhyam** [comment]
I saw that solve and reinstalled pytorch-lightning with that version but it made no difference. It seems like it didn't work in the issue you linked either though. What worked was to change something in their Trainer definition to deterministic. But I didn't see where you have something like that and also I'm not using a trainer...I'm just trying to run inference. Do you have a similar fix that can help me here?
