### ISSUE TITLE
how to test other LDR2HDR datasets like HDREye etc. ?

### ISSUE THREAD

**Issue by holastq** [VinAIResearch/single_image_hdr#5]

**Comment by hieultp** [comment]
Hi @holastq, 

For testing with different datasets, I recommend inputting the LDR image with an EV 0 into the model to generate images with EV values ranging from -2.0 to +2.0. Then merge these to create the final HDR for comparison. I suggest using Photomatix for this process, as to the best of my knowledge, tends to produce fewer artifacts in the HDR image compared to other merging methods like those in OpenCV.

**Comment by holastq** [comment]
Thanks for your instent reply! I will try it latter with best wish to you.
